// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi5JtftxDHC_kKkHVVbtPddQE_uS17L3c',
    appId: '1:800169425126:web:fa97a7dd012bd5a8a62327',
    messagingSenderId: '800169425126',
    projectId: 'gregorioexer9',
    authDomain: 'gregorioexer9.firebaseapp.com',
    storageBucket: 'gregorioexer9.appspot.com',
    measurementId: 'G-JGSX9CL96W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAax5Xi3r_Lb3plBcLEt8E7IAdww-DyeaA',
    appId: '1:800169425126:android:af3093fecb829b69a62327',
    messagingSenderId: '800169425126',
    projectId: 'gregorioexer9',
    storageBucket: 'gregorioexer9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC37TWLdqx9YJUSSeoa-iIU4v1p13lwJ0',
    appId: '1:800169425126:ios:ffb5503e1751dc25a62327',
    messagingSenderId: '800169425126',
    projectId: 'gregorioexer9',
    storageBucket: 'gregorioexer9.appspot.com',
    iosBundleId: 'com.example.gregorioexer9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC37TWLdqx9YJUSSeoa-iIU4v1p13lwJ0',
    appId: '1:800169425126:ios:ffb5503e1751dc25a62327',
    messagingSenderId: '800169425126',
    projectId: 'gregorioexer9',
    storageBucket: 'gregorioexer9.appspot.com',
    iosBundleId: 'com.example.gregorioexer9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi5JtftxDHC_kKkHVVbtPddQE_uS17L3c',
    appId: '1:800169425126:web:cc01a82cac53aa94a62327',
    messagingSenderId: '800169425126',
    projectId: 'gregorioexer9',
    authDomain: 'gregorioexer9.firebaseapp.com',
    storageBucket: 'gregorioexer9.appspot.com',
    measurementId: 'G-YKZ2YJ2XCY',
  );
}
